### ISSUE TITLE
Newlines not respected

### ISSUE THREAD

**Issue by johnmanko** [ryan-sandy/bugzilla-markdownjs#2]
newlines are not respected, which they should be.  We often cut-and-paste text, which consist of newline characters (Windows & unix).

**Comment by ryan-sandy** [comment]
Thanks for the bug, but I the newest versions of bugzilla support markdown:

http://bugzilla.readthedocs.io/en/latest/using/tips.html#markdown

**Comment by johnmanko** [comment]
@ryan-sandy Thanks. :)
